name: Flatpak CI
on:
  push:
    branches: [main]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-25.08
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: io.github.bmfrosty.mcomix.flatpak
          manifest-path: io.github.bmfrosty.mcomix.yml
          cache-key: flatpak-builder-${{ github.sha }}
